## cleaning office data for hr to predict the Salary based on parameters such as 
1. experience
2. test score
3. Interview score


In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('hr.xlsx')

In [4]:
df

Experience  Test_score  Interview_Score  Salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [15]:
updated_experience= df['Experience'].fillna('zero')

In [16]:
df['Experience']=updated_experience

In [17]:
df

Experience  Test_score  Interview_Score  Salary
0       Zero         8.0                9   50000
1       Zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [19]:
df['Experience'].unique()

array(['Zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
      dtype=object)

In [20]:
df['Experience'].map({'Zero':0, 'five':5, 'two':2, 'seven':6, 'three':3, 'ten':10, 'eleven':11})

0     0
1     0
2     5
3     2
4     6
5     3
6    10
7    11
Name: Experience, dtype: int64

In [21]:
new_experience = df['Experience'].map({'Zero':0, 'five':5, 'two':2, 'seven':6, 'three':3, 'ten':10, 'eleven':11})

In [22]:
df['Experience']= new_experience
df

Experience  Test_score  Interview_Score  Salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           6         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [48]:
new_test=df['Test_score'].fillna(df['Test_score'].mean())

In [49]:
new_test

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: Test_score, dtype: float64

In [42]:
df['Test_score']= new_test

In [43]:
df

Experience  Test_score  Interview_Score  Salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           6         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [44]:
from sklearn import linear_model
reg= linear_model.LinearRegression()
reg.fit(df[["Experience","Test_score","Interview_Score"]],df.Salary)


LinearRegression()

In [45]:
reg.predict([[5,6,7]])

array([58285.03562945])

In [46]:
reg.predict([[2,9,6]])

array([54521.20800814])

In [47]:
reg.predict([[12,10,10]])

array([92466.34996041])

In [50]:
## y= m1x1 + m2x2 + m3x3 + b